<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TripCategory;
use App\Models\Guide;
use App\Models\Trip;
use Carbon\Carbon;

class TripSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create Trip Categories
        $categories = [
            [
                'name' => 'الرحلات الجبلية',
                'slug' => 'mountain-trips',
                'description' => 'رحلات تسلق الجبال والمشي في الطبيعة',
                'icon' => 'mountain',
                'color' => '#4CAF50',
                'is_active' => true,
                'sort_order' => 1
            ],
            [
                'name' => 'الرحلات البحرية',
                'slug' => 'marine-trips',
                'description' => 'رحلات الغطس والأنشطة البحرية',
                'icon' => 'water',
                'color' => '#2196F3',
                'is_active' => true,
                'sort_order' => 2
            ],
            [
                'name' => 'الرحلات الصحراوية',
                'slug' => 'desert-trips',
                'description' => 'رحلات الصحراء والتخييم',
                'icon' => 'desert',
                'color' => '#FF9800',
                'is_active' => true,
                'sort_order' => 3
            ],
            [
                'name' => 'الرحلات التاريخية',
                'slug' => 'historical-trips',
                'description' => 'رحلات استكشاف المواقع التاريخية',
                'icon' => 'history',
                'color' => '#9C27B0',
                'is_active' => true,
                'sort_order' => 4
            ]
        ];

        foreach ($categories as $categoryData) {
            TripCategory::create($categoryData);
        }

        // Create Guides
        $guides = [
            [
                'name' => 'أحمد محمد',
                'name_en' => 'Ahmed Mohammed',
                'email' => 'ahmed@example.com',
                'slug' => 'ahmed-mohammed',
                'bio' => 'دليل سياحي محترف مع خبرة 10 سنوات في الرحلات الجبلية',
                'bio_en' => 'Professional tour guide with 10 years of experience in mountain trips',
                'experience_years' => 10,
                'rating' => 4.8,
                'specialties' => ['تسلق الجبال', 'المشي لمسافات طويلة', 'الطبيعة'],
                'specialties_en' => ['Mountain Climbing', 'Long Distance Hiking', 'Nature'],
                'languages' => ['العربية', 'الإنجليزية'],
                'certifications' => ['دليل سياحي معتمد', 'إنقاذ جبلي'],
                'total_trips' => 150,
                'is_active' => true
            ],
            [
                'name' => 'فاطمة علي',
                'name_en' => 'Fatima Ali',
                'slug' => 'fatima-ali',
                'email' => 'fatma@example.com',
                'bio' => 'خبيرة في الرحلات البحرية والغطس مع شهادات دولية',
                'bio_en' => 'Expert in marine trips and diving with international certifications',
                'experience_years' => 8,
                'rating' => 4.9,
                'specialties' => ['الغطس', 'الرياضات المائية', 'الحياة البحرية'],
                'specialties_en' => ['Diving', 'Water Sports', 'Marine Life'],
                'languages' => ['العربية', 'الإنجليزية', 'الفرنسية'],
                'certifications' => ['مدرب غطس PADI', 'إنقاذ بحري'],
                'total_trips' => 120,
                'is_active' => true
            ],
            [
                'name' => 'محمد السعد',
                'name_en' => 'Mohammed Al Saad',
                'slug' => 'mohammed-al-saad',
                'email' => 'mohamed@example.com',
                'bio' => 'دليل صحراوي خبير في الرحلات الصحراوية والتخييم',
                'bio_en' => 'Desert guide expert in desert trips and camping',
                'experience_years' => 12,
                'rating' => 4.7,
                'specialties' => ['الرحلات الصحراوية', 'التخييم', 'النجوم'],
                'specialties_en' => ['Desert Trips', 'Camping', 'Stargazing'],
                'languages' => ['العربية', 'الإنجليزية'],
                'certifications' => ['دليل صحراوي معتمد', 'إنقاذ صحراوي'],
                'total_trips' => 200,
                'is_active' => true
            ],
            [
                'name' => 'نورا أحمد',
                'name_en' => 'Nora Ahmed',
                'email' => 'noura@example.com',
                'slug' => 'nora-ahmed',
                'bio' => 'مرشدة سياحية متخصصة في التاريخ والتراث السعودي',
                'bio_en' => 'Tour guide specialized in Saudi history and heritage',
                'experience_years' => 6,
                'rating' => 4.6,
                'specialties' => ['التاريخ', 'التراث', 'المواقع الأثرية'],
                'specialties_en' => ['History', 'Heritage', 'Archaeological Sites'],
                'languages' => ['العربية', 'الإنجليزية', 'الألمانية'],
                'certifications' => ['مرشد سياحي معتمد', 'تاريخ السعودية'],
                'total_trips' => 80,
                'is_active' => true
            ]
        ];

        foreach ($guides as $guideData) {
            Guide::create($guideData);
        }

        // Create Trips
        $trips = [
            [
                'title' => 'تسلق جبل شمر',
                'title_en' => 'Climb Jabal Shammar',
                'slug' => 'climb-jabal-shammar',
                'description' => 'رحلة مميزة لتسلق جبل شمر في منطقة حائل، مع إطلالة رائعة على المناظر الطبيعية الخلابة.',
                'description_en' => 'A distinguished trip to climb Jabal Shammar in the Hail region, with breathtaking views of the scenic landscape.',
                'short_description' => 'تسلق جبل شمر في حائل',
                'short_description_en' => 'Climb Jabal Shammar in Hail',
                'price' => 450.00,
                'duration' => 2,
                'difficulty_level' => 'hard',
                'max_participants' => 15,
                'min_participants' => 5,
                'start_date' => Carbon::create(2025, 10, 30),
                'end_date' => Carbon::create(2025, 10, 30),
                'location' => 'حائل، المملكة العربية السعودية',
                'location_en' => 'Hail, Saudi Arabia',
                'meeting_point' => 'فندق حائل الدولي',
                'meeting_point_en' => 'Hail International Hotel',
                'category_id' => 1,
                'guide_id' => 1,
                'is_featured' => true,
                'is_active' => true,
                'has_story' => true,
                'type' => 'trip',
                'images' => ['images/slider-item-1.png'],
                'included_items' => ['نقل', 'إقامة', 'وجبات', 'معدات التسلق'],
                'included_items_en' => ['Transportation', 'Accommodation', 'Meals', 'Climbing Equipment'],
                'excluded_items' => ['المشروبات الشخصية', 'التأمين'],
                'excluded_items_en' => ['Personal Beverages', 'Insurance'],
                'requirements' => ['لياقة بدنية جيدة', 'خبرة في المشي'],
                'requirements_en' => ['Good Physical Fitness', 'Hiking Experience'],
                'cancellation_policy' => 'يمكن الإلغاء قبل 48 ساعة من الرحلة',
                'cancellation_policy_en' => 'Cancellation possible 48 hours before the trip',
                'rating' => 4.8,
                'total_bookings' => 25,
                'meta_title' => 'تسلق جبل شمر - رحلة مميزة في حائل',
                'meta_title_en' => 'Climb Jabal Shammar - Distinguished Trip in Hail',
                'meta_description' => 'استمتع برحلة تسلق جبل شمر في حائل مع دليل محترف',
                'meta_description_en' => 'Enjoy a trip to climb Jabal Shammar in Hail with a professional guide',
                'meta_keywords' => 'تسلق, جبل شمر, حائل, رحلات, السعودية',
                'meta_keywords_en' => 'Climbing, Jabal Shammar, Hail, Trips, Saudi Arabia'
            ],
            [
                'title' => 'غطس في البحر الأحمر',
                'title_en' => 'Red Sea Diving',
                'slug' => 'red-sea-diving',
                'description' => 'تجربة غطس لا تُنسى في مياه البحر الأحمر الصافية، مع مشاهدة الشعاب المرجانية الملونة.',
                'description_en' => 'An unforgettable diving experience in the clear waters of the Red Sea, with colorful coral reef viewing.',
                'short_description' => 'غطس في البحر الأحمر',
                'short_description_en' => 'Red Sea Diving',
                'price' => 350.00,
                'duration' => 1,
                'difficulty_level' => 'medium',
                'max_participants' => 20,
                'min_participants' => 8,
                'start_date' => Carbon::create(2025, 10, 30),
                'end_date' => Carbon::create(2025, 10, 30),
                'location' => 'جدة، المملكة العربية السعودية',
                'location_en' => 'Jeddah, Saudi Arabia',
                'meeting_point' => 'ميناء جدة البحري',
                'meeting_point_en' => 'Jeddah Sea Port',
                'category_id' => 2,
                'guide_id' => 2,
                'is_featured' => true,
                'is_active' => true,
                'has_story' => false,
                'type' => 'experience',
                'images' => ['images/slider-item-1.png'],
                'included_items' => ['معدات الغطس', 'نقل بحري', 'وجبة غداء', 'مدرب محترف'],
                'included_items_en' => ['Diving Equipment', 'Marine Transportation', 'Lunch', 'Professional Trainer'],
                'excluded_items' => ['التأمين', 'المشروبات'],
                'excluded_items_en' => ['Insurance', 'Beverages'],
                'requirements' => ['شهادة صحية', 'معرفة السباحة'],
                'requirements_en' => ['Medical Certificate', 'Swimming Knowledge'],
                'cancellation_policy' => 'يمكن الإلغاء قبل 24 ساعة',
                'cancellation_policy_en' => 'Cancellation possible 24 hours before',
                'rating' => 4.9,
                'total_bookings' => 40,
                'meta_title' => 'غطس في البحر الأحمر - جدة',
                'meta_title_en' => 'Red Sea Diving - Jeddah',
                'meta_description' => 'استمتع بتجربة غطس مميزة في البحر الأحمر',
                'meta_description_en' => 'Enjoy a distinguished diving experience in the Red Sea',
                'meta_keywords' => 'غطس, البحر الأحمر, جدة, شعاب مرجانية',
                'meta_keywords_en' => 'Diving, Red Sea, Jeddah, Coral Reefs'
            ],
            [
                'title' => 'رحلة صحراء الربع الخالي',
                'title_en' => 'Rub Al Khali Desert Trip',
                'slug' => 'rub-al-khali-desert',
                'description' => 'مغامرة صحراوية في الربع الخالي، مع التخييم تحت النجوم والاستمتاع بالهدوء الصحراوي.',
                'description_en' => 'Desert adventure in Rub Al Khali, with camping under the stars and enjoying the desert tranquility.',
                'short_description' => 'رحلة صحراء الربع الخالي',
                'short_description_en' => 'Rub Al Khali Desert Trip',
                'price' => 600.00,
                'duration' => 3,
                'difficulty_level' => 'medium',
                'max_participants' => 12,
                'min_participants' => 6,
                'start_date' => Carbon::create(2025, 11, 25),
                'end_date' => Carbon::create(2025, 11, 26),
                'location' => 'الربع الخالي، المملكة العربية السعودية',
                'location_en' => 'Rub Al Khali, Saudi Arabia',
                'meeting_point' => 'مدينة الخرج',
                'meeting_point_en' => 'Al Kharg City',
                'category_id' => 3,
                'guide_id' => 3,
                'is_featured' => true,
                'is_active' => true,
                'has_story' => true,
                'type' => 'trip',
                'images' => ['images/slider-item-1.png'],
                'included_items' => ['نقل 4x4', 'تخييم', 'وجبات', 'معدات التخييم'],
                'included_items_en' => ['4x4 Transportation', 'Camping', 'Meals', 'Camping Equipment'],
                'excluded_items' => ['المشروبات الشخصية', 'التأمين'],
                'excluded_items_en' => ['Personal Beverages', 'Insurance'],
                'requirements' => ['لياقة بدنية متوسطة', 'تحمل الحرارة'],
                'requirements_en' => ['Moderate Physical Fitness', 'Heat Tolerance'],
                'cancellation_policy' => 'يمكن الإلغاء قبل 72 ساعة',
                'rating' => 4.7,
                'total_bookings' => 18,
                'meta_title' => 'رحلة صحراء الربع الخالي',
                'meta_title_en' => 'Rub Al Khali Desert Trip',
                'meta_description' => 'مغامرة صحراوية في الربع الخالي مع التخييم',
                'meta_description_en' => 'Desert adventure in Rub Al Khali with camping',
                'meta_keywords' => 'صحراء, الربع الخالي, تخييم, نجوم',
                'meta_keywords_en' => 'Desert, Rub Al Khali, Camping, Stars'
            ],
            [
                'title' => 'جولة في الدرعية التاريخية',
                'title_en' => 'Historic Diriyah Tour',
                'slug' => 'historic-diriyah-tour',
                'description' => 'جولة تاريخية في الدرعية، مهد الدولة السعودية الأولى، مع زيارة القصور والمساجد التاريخية.',
                'description_en' => 'A historical tour in Diriyah, the cradle of the first Saudi state, with visits to historical palaces and mosques.',
                'short_description' => 'جولة في الدرعية التاريخية',
                'short_description_en' => 'Historic Diriyah Tour',
                'price' => 200.00,
                'duration' => 1,
                'difficulty_level' => 'easy',
                'max_participants' => 25,
                'min_participants' => 10,
                'start_date' => Carbon::create(2025, 11, 25),
                'end_date' => Carbon::create(2025, 11, 26),
                'location' => 'الدرعية، المملكة العربية السعودية',
                'location_en' => 'Diriyah, Saudi Arabia',
                'meeting_point' => 'بوابة الدرعية التاريخية',
                'meeting_point_en' => 'Historic Diriyah Gate',
                'category_id' => 4,
                'guide_id' => 4,
                'is_featured' => true,
                'is_active' => true,
                'has_story' => true,
                'type' => 'trip',
                'images' => ['images/slider-item-1.png'],
                'included_items' => ['دليل سياحي', 'نقل', 'وجبة غداء', 'دخول المواقع'],
                'included_items_en' => ['Tour Guide', 'Transportation', 'Lunch', 'Site Entry'],
                'excluded_items' => ['المشروبات', 'التسوق'],
                'excluded_items_en' => ['Beverages', 'Shopping'],
                'requirements' => ['لا توجد متطلبات خاصة'],
                'requirements_en' => ['No Special Requirements'],
                'cancellation_policy' => 'يمكن الإلغاء قبل 24 ساعة',
                'cancellation_policy_en' => 'Cancellation possible 24 hours before',
                'rating' => 4.6,
                'total_bookings' => 35,
                'meta_title' => 'جولة في الدرعية التاريخية',
                'meta_title_en' => 'Historic Diriyah Tour',
                'meta_description' => 'استكشف التاريخ السعودي في الدرعية',
                'meta_description_en' => 'Explore Saudi history in Diriyah',
                'meta_keywords' => 'الدرعية, تاريخ, السعودية, قصور',
                'meta_keywords_en' => 'Diriyah, History, Saudi Arabia, Palaces'
            ],
            [
                'title' => 'تسلق جبل اللوز',
                'title_en' => 'Climb Jabal Al Lawz',
                'slug' => 'climb-jabal-al-lawz',
                'description' => 'رحلة تسلق جبل اللوز في تبوك، مع إطلالة على الحدود الأردنية والمناظر الطبيعية الخلابة.',
                'description_en' => 'A climbing trip to Jabal Al Lawz in Tabuk, with views of the Jordanian border and scenic landscapes.',
                'short_description' => 'تسلق جبل اللوز في تبوك',
                'short_description_en' => 'Climb Jabal Al Lawz in Tabuk',
                'price' => 500.00,
                'duration' => 2,
                'difficulty_level' => 'expert',
                'max_participants' => 10,
                'min_participants' => 4,
                'start_date' => Carbon::create(2025, 11, 25),
                'end_date' => Carbon::create(2025, 11, 26),
                'location' => 'تبوك، المملكة العربية السعودية',
                'location_en' => 'Tabuk, Saudi Arabia',
                'meeting_point' => 'فندق تبوك الدولي',
                'meeting_point_en' => 'Tabuk International Hotel',
                'category_id' => 1,
                'guide_id' => 1,
                'is_featured' => false,
                'is_active' => true,
                'has_story' => false,
                'type' => 'trip',
                'images' => ['images/slider-item-1.png'],
                'included_items' => ['نقل', 'إقامة', 'وجبات', 'معدات التسلق'],
                'included_items_en' => ['Transportation', 'Accommodation', 'Meals', 'Climbing Equipment'],
                'excluded_items' => ['المشروبات الشخصية', 'التأمين'],
                'excluded_items_en' => ['Personal Beverages', 'Insurance'],
                'requirements' => ['لياقة بدنية ممتازة', 'خبرة في التسلق'],
                'requirements_en' => ['Excellent Physical Fitness', 'Climbing Experience'],
                'cancellation_policy' => 'يمكن الإلغاء قبل 48 ساعة',
                'cancellation_policy_en' => 'Cancellation possible 48 hours before',
                'rating' => 4.5,
                'total_bookings' => 12,
                'meta_title' => 'تسلق جبل اللوز - تبوك',
                'meta_title_en' => 'Climb Jabal Al Lawz - Tabuk',
                'meta_description' => 'رحلة تسلق جبل اللوز في تبوك',
                'meta_description_en' => 'Climbing trip to Jabal Al Lawz in Tabuk',
                'meta_keywords' => 'تسلق, جبل اللوز, تبوك, رحلات',
                'meta_keywords_en' => 'Climbing, Jabal Al Lawz, Tabuk, Trips'
            ],
            [
                'title' => 'رحلة إلى الشاطئ الساحلي',
                'title_en' => 'Coastal Beach Trip',
                'slug' => 'coastal-beach-trip',
                'description' => 'استمتع بيوم كامل على الشاطئ مع الأنشطة المائية والرياضات البحرية.',
                'description_en' => 'Enjoy a full day at the beach with water activities and marine sports.',
                'short_description' => 'رحلة إلى الشاطئ الساحلي',
                'short_description_en' => 'Coastal Beach Trip',
                'price' => 250.00,
                'duration' => 1,
                'difficulty_level' => 'easy',
                'max_participants' => 30,
                'min_participants' => 8,
                'start_date' => Carbon::create(2025, 11, 25),
                'end_date' => Carbon::create(2025, 11, 26),
                'location' => 'شاطئ الخليج، المملكة العربية السعودية',
                'location_en' => 'Gulf Beach, Saudi Arabia',
                'meeting_point' => 'الشاطئ الرئيسي',
                'meeting_point_en' => 'Main Beach',
                'category_id' => 2,
                'guide_id' => 2,
                'is_featured' => true,
                'is_active' => true,
                'has_story' => false,
                'type' => 'experience',
                'images' => ['images/slider-item-1.png'],
                'included_items' => ['معدات رياضية', 'كشك للراحة', 'وجبة غداء'],
                'included_items_en' => ['Sports Equipment', 'Rest Hut', 'Lunch'],
                'excluded_items' => ['المشروبات'],
                'excluded_items_en' => ['Beverages'],
                'requirements' => ['لا توجد متطلبات خاصة'],
                'requirements_en' => ['No Special Requirements'],
                'cancellation_policy' => 'يمكن الإلغاء قبل 12 ساعة',
                'cancellation_policy_en' => 'Cancellation possible 12 hours before',
                'rating' => 4.4,
                'total_bookings' => 50,
                'meta_title' => 'رحلة إلى الشاطئ الساحلي',
                'meta_title_en' => 'Coastal Beach Trip',
                'meta_description' => 'استمتع بيوم على الشاطئ',
                'meta_description_en' => 'Enjoy a day at the beach',
                'meta_keywords' => 'شاطئ, رياضات مائية, راحة',
                'meta_keywords_en' => 'Beach, Water Sports, Relaxation'
            ],
            [
                'title' => 'رحلة تصوير الطبيعة',
                'title_en' => 'Nature Photography Trip',
                'slug' => 'nature-photography-trip',
                'description' => 'رحلة لتصوير الطبيعة الخلابة والحياة البرية مع دليل محترف في التصوير.',
                'description_en' => 'A trip to photograph the scenic nature and wildlife with a professional photography guide.',
                'short_description' => 'رحلة تصوير الطبيعة',
                'short_description_en' => 'Nature Photography Trip',
                'price' => 400.00,
                'duration' => 1,
                'difficulty_level' => 'easy',
                'max_participants' => 15,
                'min_participants' => 5,
                'start_date' => Carbon::create(2025, 11, 25),
                'end_date' => Carbon::create(2025, 11, 26),
                'location' => 'محمية الطبيعية، المملكة العربية السعودية',
                'location_en' => 'Natural Reserve, Saudi Arabia',
                'meeting_point' => 'بوابة المحمية',
                'meeting_point_en' => 'Reserve Gate',
                'category_id' => 1,
                'guide_id' => 1,
                'is_featured' => false,
                'is_active' => true,
                'has_story' => true,
                'type' => 'experience',
                'images' => ['images/slider-item-1.png'],
                'included_items' => ['دليل تصوير', 'وجبة', 'نقل'],
                'included_items_en' => ['Photography Guide', 'Meal', 'Transportation'],
                'excluded_items' => ['كاميرا', 'معدات التصوير'],
                'excluded_items_en' => ['Camera', 'Photography Equipment'],
                'requirements' => ['كاميرا شخصية'],
                'requirements_en' => ['Personal Camera'],
                'cancellation_policy' => 'يمكن الإلغاء قبل 24 ساعة',
                'cancellation_policy_en' => 'Cancellation possible 24 hours before',
                'rating' => 4.6,
                'total_bookings' => 22,
                'meta_title' => 'رحلة تصوير الطبيعة',
                'meta_title_en' => 'Nature Photography Trip',
                'meta_description' => 'تعلم التصوير الفوتوغرافي للطبيعة',
                'meta_description_en' => 'Learn nature photography',
                'meta_keywords' => 'تصوير, طبيعة, فوتوغرافيا',
                'meta_keywords_en' => 'Photography, Nature, Photography'
            ]
        ];

        foreach ($trips as $tripData) {
            Trip::create($tripData);
        }
    }
}
